//
// Created by jire on 6/17/20.
//

#ifndef LIBMULTIROBOTPLANNING_HIGHWAY_TEST_HPP
#define LIBMULTIROBOTPLANNING_HIGHWAY_TEST_HPP

#endif  // LIBMULTIROBOTPLANNING_HIGHWAY_TEST_HPP

#include "cbs.hpp"
